### ISSUE TITLE
Type warning

### ISSUE THREAD

**Issue by hamsterdam** [bitc/vim-hdevtools#23]
Hi,

Thanks so much for making and maintaining this plugin.

When using the type command, I get the warning:
```
hdevtools#type: the buffer has been modified but not written
```

Any idea what's wrong with my setup?

**Comment by bitc** [comment]
The type command only works for files that have been saved.

So always run `:w` before using the type command. Note that the file must also be free of errors for the type command to work (otherwise it will complain).

**Comment by hamsterdam** [comment]
Ah thanks!
